global:
  scrape_interval: 15s

  external_labels:
    monitor: "aziran-mc-monitor"

scrape_configs:
  - job_name: "cAdvisor"
    scrape_interval: 5s
    static_configs:
      - targets: ["cadvisor:8080"]